# 1. 파이썬의 컴퓨팅 라이브러리, numpy
**numpy를 이용해서 데이터를 다뤄봅시다!**

### Our Goal
1. Numpy 시작하기
    - prerequisite : Python의 List
    - numpy import하기
    - numpy.array

2. Numpy로 연산하기
    - Vector - Scalar : elementwise! (+, -, *, /)
    - Vector - Vector : elementwise / broadcasting (+, -, *, /)
    - Indexing & Slicing
3. Example : Linear Algebra with Numpy
    1. basics
    - 영벡터 : `.zeros()`
    - 일벡터 : `.ones()`
    - 대각행렬 : `.diag()`
    - 항등행렬 : `.eye()`
    - 행렬곱 : `@` / `.dot()`
  
    2. furthermore
    - 트레이스 : `.trace()`
    - 행렬식 : `.linalg.det()`
    - 역행렬 : `.linalg.inv()`
    - 고유값 : `.linalg.eig()`


## I. Numpy 시작하기

### Remind: List

In [2]:
arr = [1, "two", 3.0]
print(arr)

[1, 'two', 3.0]


- 리스트는 연산 속도가 매우 느리기 때문에, 빠른 연산을 위한 C기반의 라이브러리를 따로 제작
- numpy

### numpy 모듈 불러오기

In [3]:
import numpy as np

### 왜 numpy를 사용해야 할까요?


In [4]:
# List
L = range(1000)
%timeit [i**2 for i in L]

248 µs ± 7.57 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
# numpy
# numpy.arange --> range()와 유사한 효과(with np.array)
N = np.arange(1000)
%timeit N**2

1.55 µs ± 15.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


### numpy.array

numpy의 Container, array

In [7]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [8]:
arr.shape

(3,)

In [9]:
arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arr_2d.shape

(3, 3)

## II. Numpy로 연산하기

### Vector와 Scalar 사이의 연산

벡터의 각 원소에 대해서 연산을 진행

$$
x = \begin{pmatrix}
1 \\
2 \\
3
\end{pmatrix}
\quad c = 5
$$

In [17]:
x = np.array([1,2,3])
c = 5

print(f"더하기 : {x + c}")
print(f"빼기 : {x - c}")
print(f"곱하기 : {x * c}")
print(f"나누기 : {x / c}")

더하기 : [6 7 8]
빼기 : [-4 -3 -2]
곱하기 : [ 5 10 15]
나누기 : [0.2 0.4 0.6]


### Vector와 Vector 사이의 연산

벡터의 **같은 인덱스**끼리 연산이 진행된다

$$
y = \begin{pmatrix}
1 \\
3 \\
5
\end{pmatrix}
\quad
z = \begin{pmatrix}
2 \\
9 \\
20
\end{pmatrix}
$$

In [15]:
y = np.array([1, 3, 5])
z = np.array([2, 9, 20])

print(f"더하기 : {y + z}")
print(f"빼기 : {y - z}")
print(f"곱하기 : {y * z}")
print(f"나누기 : {y / z}")

더하기 : [ 3 12 25]
빼기 : [ -1  -6 -15]
곱하기 : [  2  27 100]
나누기 : [0.5        0.33333333 0.25      ]


### Array의 Indexing

Python의 List와 유사하게 진행한다. \
[a][b] $\rightarrow$ [a, b] \

$$
W = \begin{pmatrix}
1&2&3&4 \\
5&6&7&8 \\
9&10&11&12
\end{pmatrix}
$$

In [18]:
W = np.array([[1,2,3,4], [5,6,7,8], [9, 10, 11, 12]])

print(W[0, 0])
print(W[2, 3])

# 7을 가져오기
print(W[1,2])

1
12
7


### Array의 Slicing

Python의 List와 유사하게 진행한다.

In [19]:
W = np.array([[1,2,3,4], [5,6,7,8], [9, 10, 11, 12]])

# 2 ~ 3 -> 행: 0 ~1 -> [0:2]
# 6, 7 -> 열: 1~2 -> [1:3]
W[0:2, 1:3]

array([[2, 3],
       [6, 7]])

In [22]:
print(W[0:2])
print(W[0:2, 0:4])
print(W[0:2, :])

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]


In [23]:
print(W[:, 2:4])
print(W[0:3, 2:4])

[[ 3  4]
 [ 7  8]
 [11 12]]
[[ 3  4]
 [ 7  8]
 [11 12]]


### Array의 Broadcasting
Numpy가 연산을 진행하는 특수한 방법
기본적으로 같은 Type의 data에 대해서만 연산이 적용 가능 \ 
하지만 만약 피연산자가 연산 가능하도록 변환이 가능하다면 연산이 가능해진다 \ 
이를 Broadcasting이라고 한다

### 1. M by N, M by 1

In [24]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
x = np.array([0, 1, 0])
x = x[:, None] # 전치(Transpose)를 통해 열벡터로

print(a + x)

[[1 2 3]
 [5 6 7]
 [7 8 9]]


### 2. M by N, 1 by N

In [25]:
y = np.array([0, 1, -1])

print([a * y])

[array([[ 0,  2, -3],
       [ 0,  5, -6],
       [ 0,  8, -9]])]


### 3. M by 1, 1 by N

In [26]:
t = np.array([1,2,3]) # 열벡터로 바꿔주기
t = t[:, None]
u = np.array([2, 0, -2])

print(t + u)

[[ 3  1 -1]
 [ 4  2  0]
 [ 5  3  1]]


## III. Numpy로 선형대수 지식 끼얹기

### A. basics

### 영벡터(행렬)

- 원소가 모두 0인 벡터(행렬)
- `np.zeros(dim)`을 통해 생성, dim은 값 혹은 튜플 ( , )

In [28]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### 일벡터(일행렬)

- 원소가 모두 1인 벡터(행렬)
- `np.ones(dim)`을 통해 생성, dim은 값, 튜플

In [29]:
np.ones(2)

array([1., 1.])

In [31]:
np.ones((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

### 대각행렬
-Main Diagonal을 제외한 성분이 0인 행렬
- `np.diag((main_diagonals))`을 통해 생성할 수 있음.

In [32]:
np.diag((2, 4))

array([[2, 0],
       [0, 4]])

In [33]:
np.diag((1,3,5))

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

### 항등랭렬
- main diagonal == 1인 diagonal matrix(대각행렬)
- `np.eye(n, (dtype=int, uint, float, complex, ...))`를 사용

In [34]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

### 행렬곱(dot product)
- 행렬간에 정의되는 곱연산
- `np.dot()`이나 `@`을 사용한다

In [36]:
mat_1 = np.array([[1,4], [2,3]])
mat_2 = np.array([[7,9], [0,6]])
mat_1.dot(mat_2)

array([[ 7, 33],
       [14, 36]])

In [37]:
mat_1 @ mat_2

array([[ 7, 33],
       [14, 36]])

### B. Furthermore

### 트레이스
- Main diagonal의 Sum
- `np.trace()`를 사용

In [38]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr.trace()

15

In [40]:
np.eye(3, dtype=int).trace()

3

### 행렬식(determinant)
- 행렬을 대표하는 값 중 하나
- 선형변환 과정에서 Vector의 Scailing 척도
- `np.linalg.det()`로 계산

In [42]:
arr_2 = np.array([[2,3] , [1,6]])
arr_2

array([[2, 3],
       [1, 6]])

In [43]:
np.linalg.det(arr_2)

9.000000000000002

In [44]:
arr_3 = np.array([[1, 4, 7], [2,5,8] , [3,6, 9]])
arr_3

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [45]:
np.linalg.det(arr_3)

0.0

### 역행렬
- 행렬 A에 대해서 AB = BA = I 를 만족하는 행렬 B
- `np.linalg.inv()`를 사용

In [46]:
mat = np.array([[1,4], [2,3]])
mat

array([[1, 4],
       [2, 3]])

In [49]:
mat_inv  = np.linalg.inv(mat)
mat_inv

array([[-0.6,  0.8],
       [ 0.4, -0.2]])

In [50]:
mat @ mat_inv

array([[ 1.00000000e+00,  0.00000000e+00],
       [-1.11022302e-16,  1.00000000e+00]])

### 고유값과 고유벡터(eigenvalue and eigenvector)
- 정방행렬 A에 대해서$Ax = \lambda x$를 만족하는 $\lambda$와 x를 각각 고유값과 고유벡터라 한다.
- `np.linalg.eig()`로 계산. 리턴 값 중 첫 번째 인덱스는 고유값, 두번째 인덱스는 각 열마다 고유값의 열에 대응되는 고유벡터다.

In [51]:
mat = np.array([[2, 0, -2], [1, 1, -2], [0, 0, 1]])
mat

array([[ 2,  0, -2],
       [ 1,  1, -2],
       [ 0,  0,  1]])

In [52]:
np.linalg.eig(mat)

(array([1., 2., 1.]),
 array([[0.        , 0.70710678, 0.89442719],
        [1.        , 0.70710678, 0.        ],
        [0.        , 0.        , 0.4472136 ]]))

#### 고유값과 고유벡터 검증

In [53]:
eig_val, eig_vec = np.linalg.eig(mat)

In [55]:
mat @ eig_vec[:, 0] # Ax

array([0., 1., 0.])

In [57]:
eig_val[0] * eig_vec[:, 0] # lambda x

array([0., 1., 0.])

## IV. Exercises

### 1. 어떤 벡터가 주어졌을 때 L2 norm을 구하는 함수 `get_L2_norm()`을 작성하세요

- **매개변수** : 1차원 벡터 (`np.array`)
- **반환값** : 인자로 주어진 벡터의 L2 Norm값 (`number`)

In [67]:
def get_L2_norm(vector):
    return np.sqrt(np.sum(vector**2))

In [68]:
get_L2_norm(np.array([4,5,7]))

9.486832980505138

### 2. 어떤 행렬이 singular matrix인지 확인하는 함수 `is_singular()` 를 작성하세요

- 매개변수 : 2차원 벡터(`np.array`)
- 반환값 : 인자로 주어진 벡터가 singular하면 True, non-singular하면 False를 반환 

In [69]:
def is_singular(vector):
    if not np.linalg.det(vector):
        return True
    return False

In [70]:
is_singular(np.array([[1, 4, 7], [2,5,8] , [3,6, 9]]))

True

In [71]:
is_singular(np.array([[1,4], [2,3]]))

False